spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  datasource:
    username: pgadmin
    password: pgadmin
    url: jdbc:postgresql://db.deogi:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE

